### ISSUE TITLE
HTTP2 代理可以设置 IPv4 优先吗？

### ISSUE THREAD

**Issue by pexcn** [phuslu/goproxy#1952]
从日志看来是 IPv6 优先的。

**Comment by phuslu** [comment]
嗯， ipv6 优先是 go 的默认行为，也是符合 rfc 的。

我可以加个选项来修正，尽快实现

**Comment by pexcn** [comment]
谢谢

**Comment by phuslu** [comment]
r256 加了一个选项
```toml
[default]
prefer_ipv4 = false
```
的选项，设为 true 也许可以解决这个问题。
